/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajeriacliente;

import Excepciones.ExcepcionDeAutentificacion;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Acceso extends javax.swing.JFrame {
    Cliente cliente = null;
    
    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setText("Nombre de usuario");
        jPanel4.add(jLabel4);

        username.setColumns(15);
        jPanel4.add(username);

        jPanel1.add(jPanel4);

        jLabel5.setText("Contraseña");
        jPanel5.add(jLabel5);

        pass.setColumns(15);
        jPanel5.add(pass);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Acceso a la aplicación");
        jLabel1.setMaximumSize(new java.awt.Dimension(196, 25));
        jLabel1.setMinimumSize(new java.awt.Dimension(196, 25));
        jLabel1.setPreferredSize(new java.awt.Dimension(196, 25));
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(aceptar);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cancelar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if (username.getText().isEmpty() || pass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Ninguno de los dos campos puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String password = username.getText() + "1234567890" + String.valueOf(pass.getPassword()) + "0987654321";
            byte[] passwordBytes = password.getBytes();
            try {
                MessageDigest algoritmo = MessageDigest.getInstance("MD5");
                algoritmo.reset();
                algoritmo.update(passwordBytes);
                byte[] clave = algoritmo.digest();
                StringBuilder hexString = new StringBuilder();
                for (int i=0;i<clave.length;i++) {
                   String hex = Integer.toHexString(0xFF & clave[i]); 
                   if(hex.length()==1)
                   hexString.append('0');
                   hexString.append(hex);
                }
                try {
                    cliente = new Cliente(username.getText(), hexString.toString());
                    cliente.conectar("127.0.0.1", 15000);
                    cliente.autenticar();
                    new ServicioDirectorioAutenticado(cliente).setVisible(true);
                    this.dispose();
                } catch ( IOException ex ) {
                    JOptionPane.showMessageDialog(this, "El servidor rechazó la conexión o no está operativo\n"
                            + "(" + ex.getMessage() + ")", "Error", JOptionPane.ERROR_MESSAGE);
                    cliente.cerrarConexion();
                } catch (ExcepcionDeAutentificacion ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage()
                            + "(" + ex.getMessage() + ")", "Error", JOptionPane.ERROR_MESSAGE);
                    cliente.cerrarConexion();
                }
            } catch (NoSuchAlgorithmException ex) {
                System.err.println("No se ha encontrado el algoritmo especificado");
            }
        }
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
