/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajeriacliente;

import comunes.EstadoUsuario;
import comunes.Mensaje;
import comunes.TipoMensaje;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ServicioDirectorioAutenticado extends JFrame {
    private final String nombreUsuario = "Nombre usuario";
    private final Color textFieldVacio = new Color(217, 217, 251);
    private Cliente cliente;

    /**
     * Creates new form ServicioDirectorioAutenticado
     */
    public ServicioDirectorioAutenticado(Cliente cliente) {
        initComponents();
        this.cliente = cliente;
        jLabel5.setText(cliente.getUsername());
        jLabel7.setText(cliente.getIp());
        String[] model = new String[EstadoUsuario.values().length];
        for (int i = 0; i < EstadoUsuario.values().length; i++) { model[i] = EstadoUsuario.values()[i].name(); }
        jComboBox1.setModel(new DefaultComboBoxModel(model));
        jComboBox1.setSelectedItem(EstadoUsuario.CONECTADO.name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setText("Comprobar estado de un usuario:");
        jPanel4.add(jLabel2);

        jTextField1.setColumns(13);
        jTextField1.setForeground(new java.awt.Color(217, 217, 251));
        jTextField1.setText("Nombre usuario");
        jTextField1.setMinimumSize(new java.awt.Dimension(110, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(110, 30));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel4.add(jTextField1);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel1.add(jPanel4);

        jSeparator1.setPreferredSize(new java.awt.Dimension(380, 2));
        jPanel5.add(jSeparator1);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setText("Enviar nombre, localización y estado:");
        jPanel3.add(jLabel3);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel6.add(jPanel3);

        jLabel4.setText("Nombre de usuario:");
        jPanel9.add(jLabel4);

        jLabel5.setForeground(new java.awt.Color(51, 153, 0));
        jPanel9.add(jLabel5);

        jLabel6.setText("Localización:");
        jPanel9.add(jLabel6);

        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jPanel9.add(jLabel7);

        jLabel8.setText("Estado:");
        jPanel9.add(jLabel8);
        jPanel9.add(jComboBox1);

        jPanel6.add(jPanel9);

        jPanel1.add(jPanel6);

        jSeparator2.setPreferredSize(new java.awt.Dimension(380, 2));
        jPanel7.add(jSeparator2);

        jPanel1.add(jPanel7);

        jLabel9.setText("Consultar localización de un usuario:");
        jPanel8.add(jLabel9);

        jTextField2.setColumns(13);
        jTextField2.setForeground(new java.awt.Color(217, 217, 251));
        jTextField2.setText("Nombre usuario");
        jTextField2.setMinimumSize(new java.awt.Dimension(110, 30));
        jTextField2.setPreferredSize(new java.awt.Dimension(110, 30));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel8.add(jTextField2);

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Servicio de directorio Autenticado");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if (jTextField1.getText().equals(nombreUsuario)) {
            jTextField1.setText("");
            jTextField1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().equals("")) {
            jTextField1.setText(nombreUsuario);
            jTextField1.setForeground(textFieldVacio);
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        if (jTextField2.getText().equals(nombreUsuario)) {
            jTextField2.setText("");
            jTextField2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if (jTextField2.getText().equals("")) {
            jTextField2.setText(nombreUsuario);
            jTextField2.setForeground(textFieldVacio);
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!jTextField1.getText().equals(nombreUsuario)) {
            Mensaje mensaje = cliente.comprobarEstadoUsuario(jTextField1.getText());
            if (mensaje.getTipoMensaje().equals(TipoMensaje.ERROR)) {
                JOptionPane.showMessageDialog(this, (String) mensaje.getDatos(), "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "El usuario \"" + jTextField1.getText() + "\" esta " + ((String) mensaje.getDatos()), "Estado", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes introducir un nombre de usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mensaje mensaje = cliente.enviarNombreLocalizacionYEstado(cliente.getUsername(), cliente.getIp(), (String) jComboBox1.getSelectedItem());
        if (mensaje.getTipoMensaje().equals(TipoMensaje.ERROR)) {
            JOptionPane.showMessageDialog(this, (String) mensaje.getDatos(), "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Nombre (" + cliente.getUsername() + "), localización (" + cliente.getIp() + ") y estado (" + (String) jComboBox1.getSelectedItem() + ") comunicadas con éxito", "Envio de datos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!jTextField2.getText().equals(nombreUsuario)) {
            Mensaje mensaje = cliente.consultarLocalizacionUsuario(jTextField2.getText());
            if (mensaje.getTipoMensaje().equals(TipoMensaje.ERROR)) {
                JOptionPane.showMessageDialog(this, (String) mensaje.getDatos(), "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "La localizacion del usuario \"" + jTextField1.getText() + "\" es " + ((String) mensaje.getDatos()), "Localizacion", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes introducir un nombre de usuario", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cliente.cerrarConexion();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
